framework:
    mailer:
        dsn: '%env(MAILER_DSN)%'         # Uses .env (production) by default
        envelope:
            sender: 'infoverzeilberg@gmail.com'   # SMTP sender address
        headers:
            from: 'Sander <infoverzeilberg@gmail.com>' 
