vich_uploader:
  db_driver: orm
  metadata:
    type: attribute
  mappings:
    media_object_profile_picture:
      uri_prefix: /media/profiel
      upload_destination: '%kernel.project_dir%/public/media/profiel'
      delete_on_update: true
      delete_on_remove: true
      inject_on_load: true
      # Will rename uploaded files using a unique as a suffix.
      namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
    media_object_lego:
      uri_prefix: /media/lego
      upload_destination: '%kernel.project_dir%/public/media/lego'
      delete_on_update: true
      delete_on_remove: true
      inject_on_load: true
      # Will rename uploaded files using a unique as a suffix.
      namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
