services:
###> doctrine/doctrine-bundle ###
  database:
    environment:
      # You should definitely change the password in production
    volumes:
###< doctrine/doctrine-bundle ###

volumes:
###> doctrine/doctrine-bundle ###
###< doctrine/doctrine-bundle ###
