controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
graphiql:
    path: /api/docs/graphiql
    controller: api_platform.graphql.action.graphiql

auth_login:
    path: /api/login
    controller: App\Controller\AuthController::login
    methods: ['POST']
